{% set version = "1.2.0" %}

package:
  name: recursive_diff
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/r/recursive_diff/recursive_diff-{{ version }}.tar.gz
  sha256: 42c2a3f97fb3234d952d63f7d8a54063b559ff917c762a15f15d7d45baca16bc

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - ncdiff = recursive_diff.ncdiff:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=66
    - setuptools-scm
  run:
    - python >={{ python_min }}
    - numpy >=1.16
    - pandas >=0.25
    - xarray >=0.12

test:
  imports:
    - recursive_diff
  requires:
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/crusaderky/recursive_diff
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Recursively compare two Python data structures

extra:
  recipe-maintainers:
    - crusaderky
