{% set version = "2.0.0" %}

package:
  name: recursive_diff
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/r/recursive_diff/recursive_diff-{{ version }}.tar.gz
  sha256: 5f3f707c5923d8fe13916d94d6b5eab97957cd4b0ff3c6e2c00070ef879704a3

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - recursive-diff = recursive_diff.cli.recursive_diff:main
    - ncdiff = recursive_diff.cli.ncdiff:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - numpy >=1.23
    - pandas >=1.5
    - xarray >=2023.8.0

test:
  imports:
    - recursive_diff
  commands:
    - recursive-diff --help
    - ncdiff --help
  requires:
    - python {{ python_min }}

about:
  home: https://github.com/crusaderky/recursive_diff
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Recursively compare two Python data structures

extra:
  recipe-maintainers:
    - crusaderky
