{% set version = "1.1.0" %}

package:
  name: recursive_diff
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/r/recursive_diff/recursive_diff-{{ version }}.tar.gz
  sha256: 3c21cac59b4236fca84ee817fe9e659e9c7e0fbb703a76f0b99a82d63f7f234a

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - ncdiff = recursive_diff.ncdiff:main

requirements:
  build:
    - python >=3.8
    - pip
    - setuptools-scm
  run:
    - python >=3.8
    - numpy >=1.16
    - pandas >=0.25
    - xarray >=0.12

test:
  imports:
    - recursive_diff
  requires:
    - pytest

about:
  home: https://github.com/crusaderky/recursive_diff
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Recursively compare two Python data structures

extra:
  recipe-maintainers:
    - crusaderky
