travis:
  secure:
    BINSTAR_TOKEN: LbGZ7WT/6Ayoqhd7ba32gKBAcXXaRXnOziqEKEopiJrTItQRaS1+kwjFs8hbPtlHpAyrTr9A8+ImP5X6AHftUKcQYAUVtBRhhOMtA9ZRG2ADZ6Z/J33IP3kKDOlwIvU/CCxvC42LKxbWWI0BkI+uCwJk264JHNmrQrlN+8xXAIWoPH/x4F5ByJMEEJkETRLvGwj1neoHJl9/E3XMPZRFB/McDPqZPAha1dABUnecZTHMuFMVXOpoJY50LqGm+1C7R0PHOtJzZifNMMYJuB/3alJPWDB98PQhpkjG/RRmipIIXQE1mu9K8dxdzQB1J0J1QFrVqoEsUDtn4QJS7uXJZ43Saq6B7rEvOG1emY11qzpZtTsHOy2ILhs6DvkHDVKtvPoEIiE6aW/iexWwD8DtlFviL1FNabRmT1N7dr5TfqvYOzvtMHozPcYgssPN0y8O/DYuH/nqcJGgyHWyx2IgznUSYw0sS1qxMsXbMeHIIm/v+NjSVA+DHIeqmRkjjRPtePbhr3nSTOWE3gjXrh5XJa3FtBVKQRxsmtGOCDdYCwtw7wxeDZEqgN7CntuCLKrWcZhJjOX/MMGEbRXSNCWTtj9XYZbeFET2xZKq7PqafDFMo60EGDqdQYqf5BMgJF3iw1KaF58hnrbFSb5Z4W4JbGYORl9dp+fxKKf+6Xo5NlU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
